### ISSUE TITLE
Different nesting of Enum key under experimental_strategy_and_data_subtypes property

### ISSUE THREAD

**Issue by pboutetNetrias** [CBIIT/cds-model#81]
`model-desc/cds-model-props.yml` file in 4.0.0 Branch.

For the property `experimental_strategy_and_data_subtypes` is the `Enum` key expected to be nested under `Type`?
<img width="600" alt="image" src="https://github.com/CBIIT/cds-model/assets/158093235/421d58e2-2875-47fd-b319-f387dcb2e67e">

The only other time I saw something similar to this was with the `size_of_data_being_uploaded` property. But instead of `Enum` the key was named `units`. Is this also expected?
<img width="432" alt="image" src="https://github.com/CBIIT/cds-model/assets/158093235/9dbbd8d1-39f6-489b-b3e3-d523033c964f">

**Comment by wfy1997** [comment]
It is expected for now, but will be changed in the future

**Comment by pboutetNetrias** [comment]
Enum nesting explained.
